-- Add all remaining NetSuite customer fields (standard + custom)
-- Run this in Supabase SQL Editor: https://supabase.com/dashboard/project/rpfkpxoyucocriifutfy/sql

-- Standard fields we're missing
ALTER TABLE ns_wholesale_customers
ADD COLUMN IF NOT EXISTS alcohol_recipient_type TEXT,
ADD COLUMN IF NOT EXISTS alt_name TEXT,
ADD COLUMN IF NOT EXISTS credit_hold_override TEXT,
ADD COLUMN IF NOT EXISTS date_closed DATE,
ADD COLUMN IF NOT EXISTS days_overdue_search INTEGER,
ADD COLUMN IF NOT EXISTS display_symbol TEXT,
ADD COLUMN IF NOT EXISTS is_duplicate BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS email_preference TEXT,
ADD COLUMN IF NOT EXISTS email_transactions BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS entity_number TEXT,
ADD COLUMN IF NOT EXISTS entity_title TEXT,
ADD COLUMN IF NOT EXISTS external_id TEXT,
ADD COLUMN IF NOT EXISTS fax_transactions BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS first_sale_period TEXT,
ADD COLUMN IF NOT EXISTS full_name TEXT,
ADD COLUMN IF NOT EXISTS give_access BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS global_subscription_status TEXT,
ADD COLUMN IF NOT EXISTS is_budget_approved BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_job BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_person BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS last_sale_period TEXT,
ADD COLUMN IF NOT EXISTS on_credit_hold BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS override_currency_format BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS print_transactions BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS probability NUMERIC,
ADD COLUMN IF NOT EXISTS receivables_account TEXT,
ADD COLUMN IF NOT EXISTS search_stage TEXT,
ADD COLUMN IF NOT EXISTS ship_complete BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS shipping_carrier TEXT,
ADD COLUMN IF NOT EXISTS symbol_placement TEXT,
ADD COLUMN IF NOT EXISTS is_taxable BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS top_level_parent INTEGER,
ADD COLUMN IF NOT EXISTS is_unsubscribed BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_web_lead BOOLEAN DEFAULT FALSE,

-- Custom fields (custentity_*)
ADD COLUMN IF NOT EXISTS custentity1 TEXT,
ADD COLUMN IF NOT EXISTS custentity_2663_customer_refund BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custentity_2663_direct_debit BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custentity_alf_cust_hide_service_periods BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custentity_alf_customer_hide_total_vat BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custentity_alf_customer_store_pdf BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custentity_bdc_lastupdatedbyimport BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custentity_bdc_shortname TEXT,
ADD COLUMN IF NOT EXISTS custentity_bdc_sync_exclude BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custentity_celigo_etail_cust_exported BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custentity_celigo_is_updated_via_shp BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custentity_mhi_customer_type TEXT,
ADD COLUMN IF NOT EXISTS custentity_mhi_intsagramfacebook BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS custentity_naw_trans_need_approval BOOLEAN DEFAULT FALSE;
